export enum Technology {
  JAVA = 'java',
  GROOVY = 'groovy',
  KOTLIN = 'kotlin',
  BASH = 'bash',
  PHP = 'php',
  SQL = 'sql',
  JAVA_SCRIPT = 'java script',
  TYPE_SCRIPT = 'type script',
  HAZELCAST = 'hazelcast',
  SPRING = 'spring',
  SPRING_CLOUD = 'spring cloud',
  SPRING_BOOT = 'spring boot',
  SPRING_SECURITY = 'spring security',
  ACTUATOR = 'actuator',
  SPRING_TEST = 'spring test',
  RIBBON = 'ribbon',
  EUREKA = 'eureka',
  OPEN_FEIGN = 'open feign',
  HIBERNATE = 'hibernate',
  JPA = 'jpa',
  JERSEY = 'jersey',
  O_AUTH2 = 'oAuth2',
  REST = 'rest',
  GRAPH_QL = 'graph ql',
  SOAP = 'soap',
  MONGO_DB = 'mongo db',
  MY_SQL = 'my sql',
  MS_SQL = 'ms sql',
  ORACLE = 'oracle',
  ELASTIC_SEARCH = 'elastic search',
  REDIS = 'redis',
  MEMCACHE = 'memcache',
  HADOOP = 'hadoop',
  POSTGRES = 'postgres',
  ANGULAR = 'angular',
  REACT = 'react',
  JQUERY = 'jquery',
  HTML = 'html',
  XML = 'xml',
  YAML = 'yaml',
  CSS = 'css',
  JSON = 'json',
  CSV = 'csv',
  K8S = 'kubernetes',
  OKD = 'okd',
  ARGO = 'argo',
  KAFKA = 'kafka',
  RABBIT_MQ = 'rabbit mq',
  PUBSUB = 'pubsub',
  KIBANA = 'kibana',
  GRAFANA = 'grafana',
  PROMETHEUS = 'prometheus',
  SLEUTH = 'sleuth',
  MICRO_METER = 'micro meter',
  LOMBOK = 'lombok',
  HUE = 'hue',
  HIVE = 'hive',
  SPOCK = 'spock',
  PITEST = 'pitest',
  WIRE_MOCK = 'wire_mock',
  RESTITO = 'restito',
  JUNIT = 'junit5',
  ARCHUNIT = 'archunit',
  REST_ASSURED = 'rest_assured',
  SONAR = 'sonar',
  CYPRESS = 'cypress',
  GIT = 'git',
  GITLAB = 'gitlab',
  GITHUB = 'github',
  SVN = 'svn',
  SPRING_DATA = 'spring data',
  HDFS = 'hdfs',
  PAGER_DUTY = 'pagerduty',
  AVRO = 'avro',
  HELM = 'helm',
  OPEN_SHIFT = 'open shift',
  GRAY_LOG = 'graylog',
  AWS = 'aws',
  GCP = 'GCP',
  JENKINS = 'jenkins',
  BAMBOO = 'bamboo',
  MESOS = 'mesos',
  FREEMARKER = 'freemarker',
  THYMELEAF = 'thymeleaf',
  MAVEN = 'maven',
  GRADLE = 'gradle',
  NPM = 'npm',
  BITBUCKET = 'bitbucket',
  SPLUNK = 'splunk',
  CLOUDFLARE = 'cloudflare',
  JOOQ = 'jooq',
  // infrastructure
  CI_CD = 'CI/CD',
  BLUE_GREEN_DEPLOYMENT = 'Blue green deployment',
  MONITORING = 'Monitoring',
  // backend frameworks / libraries
  SLF4J = 'SLF4J',
  LOGBACK = 'logback',
  CAMEL = 'camel',
  MULTI_THREADING = 'multi threading',
  // programming techniques
  TDD = 'TDD',
  DDD = 'DDD',
  PAIR_PROGRAMMING = 'PAIR PROGRAMMING',
  SOLID = 'SOLID',
  KISS = 'KISS',
  CLEAN_CODE = 'CLEAN CODE',
  DRY = 'DRY',
  YAGNI = 'YAGNI',
  EVENT_STORMING = 'Event storming',
  // other tools / environment
  BIG_DATA = 'Big data',
  TESTING_UNIT = 'Testing UNIT',
  TESTING_INTEGRATION = 'Testing INTEGRATION',
  TESTING_E2E = 'Testing E2E',
  AB_TESTING = 'A/B testing',
  ARCHITECTURE = 'Architecture',
  QUALITY = 'Quality',
  WORDPRESS = 'WordPress',
  LINUX = 'linux',
  MAC_OSX = 'MacOsx',
  INTELLIJ = 'IntelliJ',
  // AI tools
  CHAT_GPT = 'ChatGPT',
  GITHUB_COPILOT = 'GitHub Copilot',
  CLAUDE_CODE = 'Claude Code',
  GEMINI = 'Gemini',
  BUILDING_AGENTS = 'Building Agents',
  CREATING_SKILLS = 'Creating Skills',
  CREATING_WORKFLOWS = 'Creating workflows',
  MCP = 'MCP',
}

export enum ApplicationArchitecture {
  HEXAGONAL_ARCHITECTURE = 'HEXAGONAL ARCHITECTURE',
  ONION_ARCHITECTURE = 'ONION ARCHITECTURE',
  MVC = 'MVC',
  LAYERED_ARCHITECTURE = 'LAYERED ARCHITECTURE',
  PIPE_AND_FILTERS = 'PIPE AND FILTERS',
  MICRO_CARNAL = 'MICRO CARNAL',
  CQRS = 'CQRS',
  OTHER = 'OTHER',
}

export enum SystemArchitecture {
  MONOLITH = 'monolith',
  MICROSERVICES = 'microservices',
  MICRO_MONOLITH = 'micro monolith',
}

export enum Methodology {
  AGILE = 'agile',
  LEAN = 'lean',
  SCRUM = 'scrum',
  KANBAN = 'kanban',
  WATERFALL = 'waterfall',
  SAFE = 'safe',
  XP = 'xp',
}
